# Generated by Django 3.2 on 2021-04-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(upload_to='questions')),
                ('option1', models.ImageField(upload_to='questions')),
                ('option2', models.ImageField(upload_to='questions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.subject')),
            ],
        ),
    ]
