# Generated by Django 3.2 on 2021-04-23 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(upload_to='media/images/questions')),
                ('option1', models.ImageField(upload_to='questions', verbose_name='Option 1')),
                ('option2', models.ImageField(upload_to='questions', verbose_name='Option 2')),
                ('option3', models.ImageField(upload_to='questions', verbose_name='Option 3')),
                ('option4', models.ImageField(upload_to='questions', verbose_name='Option 4')),
                ('difficulty', models.IntegerField(choices=[(0, 'Bilinmiyor'), (1, 'Easy'), (2, 'Intermediate'), (3, 'Hard')])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.subject', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
