# Generated by Django 3.2 on 2021-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Bilinmiyor'), (1, 'Kolay'), (2, 'Orta'), (3, 'Zor')]),
        ),
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.ImageField(upload_to='images/questions', verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.ImageField(upload_to='images/questions', verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.ImageField(upload_to='images/questions', verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.ImageField(upload_to='images/questions', verbose_name='Option 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.ImageField(upload_to='images/questions'),
        ),
    ]
