# Generated by Django 3.0 on 2021-04-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='LectureSchedule',
        ),
    ]
