# Generated by Django 3.0 on 2021-04-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='binary_code',
        ),
    ]
