# Generated by Django 3.0 on 2021-04-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_country_binary_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='plate_no',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='binary_code',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='triple_code',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
