# Generated by Django 3.0 on 2021-04-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20210424_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureschedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Teacher'),
        ),
    ]
