# Generated by Django 3.0 on 2021-04-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_lectureschedule_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureschedule',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
