# Generated by Django 3.0 on 2021-04-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20210424_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureschedule',
            name='test',
        ),
    ]
